#cloud-config

---
write-files:
  - path: /home/core/bin/find-ip4.sh
    permissions: '0755'
    content: |
      #!/bin/sh
      IFACE="${1}"
      FILE="${2}"
      VARIABLE="${3}"
      while [ -z "${ip}" ]; do
        ip=$(ip -4 -o addr show dev "${IFACE}" scope global | \
          gawk '{split ($4, out, "/"); print out[1]}')
        sleep .1
      done
      echo "${ip}"
      sed -i -e "/^${VARIABLE}=/d" "${FILE}"
      echo "${VARIABLE}=${ip}" >> "${FILE}"

manage_etc_hosts: "localhost"
coreos:
  oem:
    id: "corectl"
    version_id: "@@version@@"
    name: "CoreOS over OS X made simple"
    home-url: "https://github.com/TheNewNormal/corectl"
    bug-report-url: "https://github.com/TheNewNormal/corectl/issues/"
  units:
  - name: update-engine.service
    command: stop
  - name: locksmithd.service
    command: stop
  - name: corectl-set-hostname.service
    command: start
    content: |
      [Unit]
      Description=Sets Hostname from /proc/cmdline
      ConditionKernelCommandLine=corectl.hostname
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      StandardOutput=journal+console
      ExecStart=/bin/bash -c " [[ $$(</proc/cmdline) =~ \
        corectl.hostname=([^\\ ]+) ]]; \
        /usr/bin/hostnamectl set-hostname $${BASH_REMATCH[1]} "
      [Install]
      WantedBy=local.target
  - name: corectl-ssh-key.service
    command: start
    content: |
      [Unit]
      Description=Loads corectl private ssh key from /proc/cmdline
      Requires=coreos-setup-environment.service
      After=coreos-setup-environment.service
      ConditionKernelCommandLine=corectl.ssh
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      StandardOutput=journal+console
      ExecStart=/bin/bash -c " [[ $$(</proc/cmdline) =~ \
        corectl.ssh=\\\"([^\\\"]+)\\\" ]]; echo $${BASH_REMATCH[1]} | \
        update-ssh-keys -a corectl.ssh "
      [Install]
      WantedBy=local.target
  - name: phone-home.service
    command: start
    content: |
      [Unit]
      Description=Tell corectld that this machine is online.
      Requires=coreos-setup-environment.service
      After=coreos-setup-environment.service
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      StandardOutput=journal+console
      ExecStart=/home/core/bin/find-ip4.sh eth0 \
        /etc/environment COREOS_PRIVATE_IPV4
      ExecStart=/home/core/bin/find-ip4.sh eth0 \
        /etc/environment COREOS_PUBLIC_IPV4
      ExecStart=/bin/bash -c " [[ $$(</proc/cmdline) =~ \
        corectl.endpoint=([^\\ ]+) ]]; curl -Ls $${BASH_REMATCH[1]}/ping "
  - name: corectl-host-homedir-sharing.service
    command: restart
    runtime: yes
    content: |
      [Unit]
      Description=Mounts host's caller homedir via NFS
      Requires=coreos-setup-environment.service
      After=coreos-setup-environment.service
      ConditionKernelCommandLine=corectl.sharedhomedir=true
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/bin/bash -c " [[ $$(</proc/cmdline) =~ \
        corectl.endpoint=([^\\ ]+) ]]; \
        /usr/bin/coreos-cloudinit -from-url $${BASH_REMATCH[1]}/homedir "
      [Install]
      WantedBy=local.target
